SSL check using a CA path parameter
privacyidea/FreeRADIUS pull request #59
Opened 2022-02-03 14:23 UTC by lferrarotti74

Get rid of the SSL check using also a path where the CA files are located and used for validating the SSL certificate of the PI server.

2022-02-24 14:17 UTC, cornelinux requested changes

2022-02-24 14:17 UTC, cornelinux commented on privacyidea_radius.pm
> +            $ua->ssl_opts( SSL_ca_path => $SSL_CA_PATH, verify_hostname => 1 );
The ssl_opts should only be set, if the SSL_CA_PATH is set, to ensure, that the system wide CAs are used, if SSL_CA_PATH is not set.
So the above if-statement should also check, if SSLA_CA_PATH is set at all.

2022-03-23 12:21 UTC, lferrarotti74 commented
I hope this changes are more near what you were expecting and requesting

2022-07-11 16:41 UTC, cornelinux approved these changes

2022-10-25 10:07 UTC, merged